version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.0.0

    working_directory: ~/intercom-rails

    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake
